// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    CAPTCHA_SITE_SECRET_KEY: string;
    VERIFY_ENDPOINT: string;
    SIGNER_PRIVATE_KEY: string;
    NETWORK_CHAIN_ID: string;

    CONTRACT_ADDRESS: string;
    CONTRACT_DOMAIN: string;
    CONTRACT_VERSION: string;
}
